In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv("C:/Users/Tas/Desktop/progs/data/decisiontree.csv")
df

Company                  Job     Degree  Salary_more_than_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook   computer programme  bachelors                      1
15    facebook   computer programme    masters                      1

In [5]:
inputs =df.drop('Salary_more_than_100k',axis='columns')
inputs

Company                  Job     Degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook   computer programme  bachelors
15    facebook   computer programme    masters

In [6]:
target= df['Salary_more_than_100k']
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: Salary_more_than_100k, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder


In [13]:
le_company=LabelEncoder()
le_job=LabelEncoder()
le_degree=LabelEncoder()

In [14]:
inputs['company_encoded']=le_company.fit_transform(inputs['Company'])
inputs['job_encoded']=le_job.fit_transform(inputs['Job'])
inputs['degree_encoded']=le_degree.fit_transform(inputs['Degree'])
inputs

Company                  Job     Degree  company_encoded  job_encoded  \
0       google      sales executive  bachelors                2            3   
1       google      sales executive    masters                2            3   
2       google     business manager  bachelors                2            0   
3       google     business manager    masters                2            0   
4       google  computer programmer  bachelors                2            2   
5       google  computer programmer    masters                2            2   
6   abc pharma      sales executive    masters                0            3   
7   abc pharma  computer programmer  bachelors                0            2   
8   abc pharma     business manager  bachelors                0            0   
9   abc pharma     business manager    masters                0            0   
10    facebook      sales executive  bachelors                1            3   
11    facebook      sales executive    masters                1            3   
12    facebook     business manager  bachelors                1            0   
13    facebook     business manager    masters                1            0   
14    facebook   computer programme  bachelors                1            1   
15    facebook   computer programme    masters                1            1   

    degree_encoded  
0                0  
1                1  
2                0  
3                1  
4                0  
5                1  
6                1  
7                0  
8                0  
9                1  
10               0  
11               1  
12               0  
13               1  
14               0  
15               1

In [15]:
from sklearn import tree

In [16]:
input_n=inputs.drop(['Company','Job','Degree'],axis='columns')
input_n

company_encoded  job_encoded  degree_encoded
0                 2            3               0
1                 2            3               1
2                 2            0               0
3                 2            0               1
4                 2            2               0
5                 2            2               1
6                 0            3               1
7                 0            2               0
8                 0            0               0
9                 0            0               1
10                1            3               0
11                1            3               1
12                1            0               0
13                1            0               1
14                1            1               0
15                1            1               1

In [18]:
model=tree.DecisionTreeClassifier()

In [19]:
model.fit(input_n,target)

DecisionTreeClassifier()

In [20]:
model.predict([[2,1,0]])

array([1], dtype=int64)

In [22]:
model.predict([[2,1,1]])

array([1], dtype=int64)

In [23]:
model.predict([[1,1,1]])

array([1], dtype=int64)